# theme = "native"
# theme = 'plain'
# theme = 'solarized-dark'
# theme = 'slick'
# theme = 'modern'
# theme = 'bad-wolf'
# theme = 'gruvbox-dark'
# theme = 'space-villain'
theme = 'semi-native'
# theme = 'nord-dark'
# theme = 'dracula'
icons = "none"

[[block]]
block = "focused_window" 
max_width = 50 
show_marks = "visible"

[[block]]
block = "sound"


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"


[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
format = "{percentage} "
