theme = "native"
icons = "material"


[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"


[[block]]
block = "sound"


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5



[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
format = "{percentage} "
